### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by gitphantomman** [gitphantomman/my_backend#4]
After email verification, I have to receive 6-digits, no token.
Then there haven't be a link. And user manually input 6-digits.

**Comment by BitVoyagerMan** [comment]
Okay, it there any verified email for node-mailer?

**Comment by gitphantomman** [comment]
Yes, there is.
And there're also api keys.

**Comment by BitVoyagerMan** [comment]
Great! let me try with this issue.
